In [34]:
#!/usr/bin/env python
"""
Retrieve intraday stock data from Google Finance.
"""

import csv
import datetime
import re

import pandas as pd
import requests
import codecs



def get_google_finance_intraday(ticker, period, days=10):
    """
    Retrieve intraday stock data from Google Finance.
    Parameters
    ----------
    ticker : str
        Company ticker symbol.
    period : int
        Interval between stock values in seconds.
    days : int
        Number of days of data to retrieve.
    Returns
    -------
    df : pandas.DataFrame
        DataFrame containing the opening price, high price, low price,
        closing price, and volume. The index contains the times associated with
        the retrieved price values.
    """
    #CHANGE THE P VARIABLE IN ORDER TO GO FURTHER BACK IN TIME
    #for example, p=15 means 15 business days ago
    uri = "http://www.google.com/finance/getprices?q="+ticker+"&i=400&p="+period+"d&f=d,o,h,l,c,v"
    page = requests.get(uri)
    reader = csv.reader(codecs.iterdecode(page.content.splitlines(), "utf-8"))
    columns = ['Open', 'High', 'Low', 'Close', 'Volume']
    rows = []
    times = []
    for row in reader:
        if re.match('^[a\d]', row[0]):
            if row[0].startswith('a'):
                start = datetime.datetime.fromtimestamp(int(row[0][1:]))
                times.append(start)
            else:
                times.append(start+datetime.timedelta(seconds=int(period)*int(row[0])))
            rows.append(map(float, row[1:]))
    if len(rows):
        return pd.DataFrame(rows, index=pd.DatetimeIndex(times, name='Date'),
                            columns=columns)
    else:
        return pd.DataFrame(rows, index=pd.DatetimeIndex(times, name='Date'))

In [36]:
get_google_finance_intraday("AAPL","60")

                       Open      High       Low     Close    Volume
Date
2017-09-06 13:00:00  161.91  162.9900  160.5200  162.7100  21651726
2017-09-06 13:01:00  161.26  162.2400  160.3600  162.0900  21928502
2017-09-06 13:02:00  158.63  161.1500  158.5300  160.8600  28611535
2017-09-06 13:05:00  161.50  162.0500  159.8900  160.5000  31580798
2017-09-06 13:06:00  160.86  163.9600  158.7700  162.6100  71714046
2017-09-06 13:07:00  159.65  159.9600  157.9100  159.8700  44907361
2017-09-06 13:08:00  158.28  159.4000  158.0900  158.9900  23760749
2017-09-06 13:09:00  159.88  160.9700  158.0000  158.4700  49114602
2017-09-06 13:12:00  158.67  160.5000  157.9950  160.1100  28269435
2017-09-06 13:13:00  158.73  159.7700  158.4400  159.5100  20810632
2017-09-06 13:14:00  156.07  158.2600  153.8300  157.9000  52951364
2017-09-06 13:15:00  153.39  155.8000  152.7500  155.8000  37511661
2017-09-06 13:16:00  151.89  152.2700  150.5600  151.5375  46645443
2017-09-06 13:19:00  150.55  151.8300  149.1600  149.9900  44387336
2017-09-06 13:20:00  153.14  153.9200  151.6900  151.7800  36660045
2017-09-06 13:21:00  154.23  154.7189  153.5400  153.8000  25182779
2017-09-06 13:22:00  153.28  154.2800  152.7000  153.8900  22005455
2017-09-06 13:23:00  154.12  154.1300  152.0000  153.2100  26299810
2017-09-06 13:26:00  153.81  154.4500  152.7200  154.2600  18698842
2017-09-06 13:27:00  154.48  155.0900  153.9100  154.0100  16230293
2017-09-06 13:28:00  153.48  153.8600  152.4600  153.6300  20163750
2017-09-06 13:29:00  155.39  155.4400  154.0500  154.1800  21283769
2017-09-06 13:30:00  155.30  155.4900  154.5600  154.9700  17407558
2017-09-06 13:33:00  155.84  156.7300  155.4850  155.8100  16262923
2017-09-06 13:34:00  155.90  158.0000  155.1000  156.0550  15617014
2017-09-06 13:35:00  156.55  156.9800  155.7500  155.9700  16905640
2017-09-06 13:36:00  156.00  157.3700  155.7299  156.3500  16125054
2017-09-06 13:37:00  156.99  157.2800  156.4100  156.7300  16394188
2017-09-06 13:40:00  159.88  160.0000  157.6500  157.9000  24121452
2017-09-06 13:41:00  160.47  160.8700  159.2300  159.7800  18997275
2017-09-06 13:42:00  159.76  160.7100  159.6000  160.4200  16374164
2017-09-06 13:43:00  155.98  157.0800  155.0200  156.7500  42584166
2017-09-06 13:44:00  156.25  157.7500  155.9600  156.6100  23974146
2017-09-06 13:47:00  156.17  157.6900  155.5000  156.8900  21984327
2017-09-06 13:48:00  157.10  157.4200  156.2000  156.2900  17757230
2017-09-06 13:49:00  156.41  157.5500  155.2700  156.9100  21207098
2017-09-06 13:50:00  157.41  157.8295  156.7800  157.2300  17000469
2017-09-06 13:51:00  163.05  163.6000  158.7000  159.2900  44454160
2017-09-06 13:54:00  166.72  168.0700  163.7200  163.8900  44700772
2017-09-06 13:55:00  169.04  169.6499  166.9400  167.9000  36046828
2017-09-06 13:56:00  166.89  169.9400  165.6100  169.8700  33637762
2017-09-06 13:57:00  168.11  168.5000  165.2800  166.6000  41393373
2017-09-06 13:58:00  172.50  174.2600  171.1200  174.0000  59398631
2017-11-06 13:00:00  174.25  174.9900  171.7200  172.3650  35026306
2017-11-06 13:01:00  174.81  175.2500  173.6000  173.9100  24361485
2017-11-06 13:02:00  176.24  176.2400  174.3300  174.6600  24409527
2017-11-06 13:03:00  175.88  176.0950  173.1400  175.1100  29482596
2017-11-06 13:04:00  174.67  175.3800  174.2700  175.1100  25145500
2017-11-06 13:07:00  173.97  174.5000  173.4000  173.5000  16982080
2017-11-06 13:08:00  171.34  173.4800  171.1800  173.0400  23756533